"""Added Profile table

Revision ID: b4f9e48278b5
Revises:
Create Date: 2022-02-22 20:07:45.397135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b4f9e48278b5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sex", sa.Integer(), nullable=True),
        sa.Column("number_of_purchases", sa.Integer(), nullable=True),
        sa.Column("avg_price_of_cart", sa.Integer(), nullable=True),
        sa.Column("days_since_last_purchase", sa.Integer(), nullable=True),
        sa.Column("last_purchase_date", sa.DateTime(), nullable=True),
        sa.Column("average_days_beetween_purchases", sa.Integer(), nullable=True),
        sa.Column("average_number_of_purchases", sa.Integer(), nullable=True),
        sa.Column("device_list", sa.Integer(), nullable=True),
        sa.Column("locations_list", sa.String(), nullable=True),
        sa.Column("last_seen_location", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profiles")
    # ### end Alembic commands ###
