name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:13.0
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: lenyagolikov
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: profile
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5    

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements.dev.txt
    - name: Lint with flake8
      run: |
        flake8
    - name: Test with pytest
      run: |
        pytest
